import type { ScanReport } from "./types";
import { gradeMeaning, verdictFromScore } from "./verdict";

export function reportToMarkdown(report: ScanReport, reportUrl?: string): string {
  const verdict = verdictFromScore(report.score, report.findings);
  const lines: string[] = [];

  lines.push(`# ShipCheck report — ${report.repo.owner}/${report.repo.repo}`);
  lines.push("");
  lines.push(`**Verdict:** ${verdict.label} — ${verdict.headline}`);
  lines.push(
    `**Ship score:** ${report.score.overall}/100 (grade ${report.score.grade}) — ${gradeMeaning(report.score.grade)}`,
  );
  lines.push(`**Scanned:** ${report.repo.scannedFiles}/${report.repo.totalFiles} files`);
  lines.push(`**Repo:** ${report.repo.htmlUrl}`);
  if (reportUrl) lines.push(`**Report:** ${reportUrl}`);
  lines.push("");
  lines.push("## Summary");
  lines.push(report.summary);
  lines.push("");
  lines.push("## Analyst note");
  lines.push(`> ${report.vibeCoderRoast}`);
  lines.push("");

  if (report.shipScenario) {
    lines.push("## If you ship tonight");
    lines.push(`**${report.shipScenario.headline}**`);
    lines.push("");
    lines.push(report.shipScenario.story);
    lines.push("");
    lines.push("### Blast radius");
    for (const b of report.shipScenario.blastRadius) lines.push(`- ${b}`);
    lines.push("");
    lines.push("### First 72 hours");
    for (const b of report.shipScenario.first72Hours) lines.push(`- ${b}`);
    lines.push("");
    lines.push(`**Founder move:** ${report.shipScenario.founderMove}`);
    lines.push("");
  }

  lines.push("## Score breakdown");
  lines.push(`- Security: ${report.score.breakdown.security}`);
  lines.push(`- Production: ${report.score.breakdown.production}`);
  lines.push(`- Best practices: ${report.score.breakdown.bestPractices}`);
  lines.push("");

  lines.push(`## Findings (${report.findings.length})`);
  if (report.findings.length === 0) {
    lines.push("_No high-signal findings in this pass._");
  } else {
    report.findings.forEach((f, i) => {
      lines.push("");
      lines.push(`### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}`);
      lines.push("");
      if (f.simpleExplain) {
        lines.push(`**In plain English:** ${f.simpleExplain}`);
        lines.push("");
      }
      if (f.businessImpact) {
        lines.push(`**Business impact:** ${f.businessImpact}`);
        lines.push("");
      }
      if (f.analogy) {
        lines.push(`**Analogy:** ${f.analogy}`);
        lines.push("");
      }
      lines.push(`**Technical:** ${f.description}`);
      lines.push("");
      lines.push(`**How to fix:** ${f.recommendation}`);
      if (f.file) {
        lines.push("");
        lines.push(`**Where:** \`${f.file}${f.line ? `:${f.line}` : ""}\``);
      }
    });
  }

  if (report.fixPatches?.length) {
    lines.push("");
    lines.push("## AI fix patches");
    report.fixPatches.forEach((p, i) => {
      lines.push("");
      lines.push(`### Patch ${i + 1}: ${p.title}`);
      lines.push("");
      lines.push(p.explanation);
      lines.push("");
      lines.push(`\`\`\`${p.language}`);
      lines.push(p.code);
      lines.push("```");
    });
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by ShipCheck — production readiness for AI-built software._");
  return lines.join("\n");
}
